kind: App
apiVersion: appctl.io/v1
metadata:
  name: users-service
  annotations:
    author: appct-examples-author
    description: users-service description
    organization: my-org
spec:
  templates:
  - nodejs
  - docker
  vars:
    - name: CONTAINER_IMAGE_NAME
      value: appctl-users-service:latest
  recipes:
    all:
      - name: nodejs
        template: nodejs
        recipes: [build]
      - name: docker
        template: docker
        recipes: [build, push]