kind: App
apiVersion: appctl.io/v2
metadata:
  name: microservices-example
  annotations:
    author: appct-examples-author
    description: microservices-example description
    organization: my-org
spec:
  recipes:
    build:
      description: Complete build of all the apps and their respective container images
      steps:
        - name: build container images for all microservices
          template: appctl
          recipes:
            - nodejs/build
            - docker/build
            # - push # uncomment to run docker push on all projects
          apps:
            - api-gateway
            - fruits-service
            - users-service