kind: App
apiVersion: appctl.io/v1
metadata:
  name: microservices-example
  annotations:
    author: appct-examples-author
    description: microservices-example description
    organization: my-org
spec:
  recipes:
    build:
      - name: build container images for all microservices
        template: appctl
        recipes:
          - nodejs/build
          - docker/build
          # - push # uncomment to run docker push on all projects
        apps:
          - api-gateway
          - fruits-service
          - users-service