kind: App
apiVersion: appctl.io/v1
metadata:
  name: simple-app
  annotations:
    author: simple-app author
    description: simple-app description
    organization: simple-app-org
spec:
  template: quarkus-jvm
  vars:
    - name: CONTAINER_IMAGE_NAME
      value: simple-app:latest
  recipes:
    overload:
      - template: quarkus-jvm
        recipe: build
        vars:
          - name: CONTAINER_IMAGE_NAME
            value: simple-app-appctl-test:latest
    push: 
      - template: docker
        recipe: push