kind: App
apiVersion: appctl.io/v1
metadata:
  name: simple-app
  annotations:
    author: simple-app author
    description: simple-app description
    organization: famargon
spec:
  template: quarkus-jvm
  vars:
    - name: CONTAINER_IMAGE_TAG
      value: latest
  recipes:
    overload:
      - template: quarkus-jvm
        recipe: build
        vars:
          - name: CONTAINER_IMAGE_TAG
            value: appctl-test
    push: 
      - template: docker
        recipe: push
        vars:
          - name: CONTAINER_IMAGE_TAG
            value: appctl-test