kind: App
apiVersion: appctl.io/v1
metadata:
  name: fruits-service
  annotations:
    author: appct-examples-author
    description: fruits-service description
    organization: my-org
spec:
  templates:
  - nodejs
  - docker
  vars:
    - name: CONTAINER_IMAGE_NAME
      value: appctl-fruits-service:latest
